
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x88\x81%\x85<\xf6\x1fb)s_\x8d\xe3l\xe8\x00'
    
_lr_action_items = {'STRING':([0,4,5,7,8,12,],[1,1,-2,-3,-1,-4,]),'SEMI':([9,10,13,],[12,-9,-8,]),'INT':([0,4,5,7,8,12,],[2,2,-2,-3,-1,-4,]),'CHAR':([0,4,5,7,8,12,],[3,3,-2,-3,-1,-4,]),'COMMA':([9,10,13,],[11,-9,-8,]),'ID':([1,2,3,6,11,],[-7,-5,-6,10,13,]),'$end':([4,5,7,8,12,],[0,-2,-3,-1,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'id_list':([6,],[9,]),'program':([0,],[4,]),'type':([0,4,],[6,6,]),'variable_declaration':([0,4,],[7,7,]),'global_statement':([0,4,],[5,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program global_statement','program',2,'p_program','C:/wamp/wamp/www/vype/vypeparser.py',102),
  ('program -> global_statement','program',1,'p_program','C:/wamp/wamp/www/vype/vypeparser.py',103),
  ('global_statement -> variable_declaration','global_statement',1,'p_global_statement','C:/wamp/wamp/www/vype/vypeparser.py',116),
  ('variable_declaration -> type id_list SEMI','variable_declaration',3,'p_variable_declaration','C:/wamp/wamp/www/vype/vypeparser.py',123),
  ('type -> INT','type',1,'p_type','C:/wamp/wamp/www/vype/vypeparser.py',136),
  ('type -> CHAR','type',1,'p_type','C:/wamp/wamp/www/vype/vypeparser.py',137),
  ('type -> STRING','type',1,'p_type','C:/wamp/wamp/www/vype/vypeparser.py',138),
  ('id_list -> id_list COMMA ID','id_list',3,'p_id_list','C:/wamp/wamp/www/vype/vypeparser.py',144),
  ('id_list -> ID','id_list',1,'p_id_list','C:/wamp/wamp/www/vype/vypeparser.py',145),
]
